import os
import json
from fastapi import FastAPI, Header, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from dotenv import load_dotenv
from openai import OpenAI

from instructions import SYSTEM_INSTRUCTIONS
from normalizer import build_normalized_context
from schemas import AuditRequest, AuditResponse

load_dotenv()

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")
PROXY_API_KEY = os.getenv("PROXY_API_KEY")
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4.1-mini")

if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY is missing")

client = OpenAI(api_key=OPENAI_API_KEY)

app = FastAPI(title="Zipline Audit API - Optimized")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
def health_check():
    return {"status": "ok", "service": "zipline-audit-api-optimized"}


def verify_proxy_key(x_api_key: str | None):
    if PROXY_API_KEY and x_api_key != PROXY_API_KEY:
        raise HTTPException(status_code=401, detail="Invalid API key")


@app.post("/audit", response_model=AuditResponse)
def audit_order(
    payload: AuditRequest,
    x_api_key: str | None = Header(default=None),
):
    # verify_proxy_key(x_api_key) # Enforce this in the future

    normalized = build_normalized_context(
        whatsapp_message=payload.whatsappMessage,
        fulfillment_confirmation=payload.fulfillmentConfirmation,
        osu_items=payload.osuItems,
    )

    prompt = f"""
Compare the two raw inputs and use the normalized context as supporting evidence.

=== RAW WHATSAPP SOURCE MESSAGE ===
{payload.whatsappMessage}

=== RAW FULFILMENT RECIPIENT SYSTEM LOG ===
{payload.fulfillmentConfirmation}

=== NORMALIZED CONTEXT GENERATED BY API ===
{json.dumps(normalized, indent=2)}

=== ACTIVE OUT-OF-STOCK ITEMS AS PROVIDED ===
{payload.osuItems}
"""

    try:
        response = client.responses.parse(
            model=OPENAI_MODEL,
            input=[
                {"role": "system", "content": SYSTEM_INSTRUCTIONS},
                {"role": "user", "content": prompt},
            ],
            text_format=AuditResponse,
            temperature=0,
        )
        return response.output_parsed

    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
